config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :recipes

  root 'recipes#index'
  # root 'welcome#index'

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/ingredient.rb
class Ingredient < ActiveRecord::Base
  belongs_to :recipe
end

app/models/instruction.rb
class Instruction < ActiveRecord::Base
  belongs_to :recipe
end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
  has_many :ingredients
  has_many :instructions
  belongs_to :user

  accepts_nested_attributes_for :ingredients, reject_if: proc { |attributes| attributes['name'].blank? }, allow_destroy: true
  accepts_nested_attributes_for :instructions, reject_if: proc { |attributes| attributes['step'].blank? }, allow_destroy: true

  validates :title, :description, :image, presence: true

  has_attached_file :image, styles: { medium: '350x200#', large: '800x500#' }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  
  attr_accessor :login
  
  has_many :recipes

  def login=(login)
    @login = login
  end

  def login
    @login || self.username || self.email
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:username, :email, :password, :password_confirmation, :remember_me) }
    devise_parameter_sanitizer.for(:sign_in) { |u| u.permit(:login, :username, :email, :password, :remember_me) }
    devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:username, :email, :password, :password_confirmation, :current_password) }
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :find_recipe, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:edit, :update, :new, :create, :destroy]

  def index
    @recipe = Recipe.all.order('updated_at desc')
  end

  def edit
  end

  def update
    if @recipe.update(recipe_params)
      flash[:success] = 'Successfully updated recipe'
      redirect_to @recipe
    else 
      render 'edit'
    end
  end

  def new
    @recipe = current_user.recipes.build
  end

  def create
    @recipe = current_user.recipes.build(recipe_params)

    if @recipe.save
      flash[:success] = 'Successfully added new recipe'
      redirect_to @recipe
    else
      render 'new'
    end
  end

  def show
  end

  def destroy
    @recipe.destroy

    flash[:success] = 'Successfully deleted recipe'
    redirect_to root_path
  end

  private

    def find_recipe
      @recipe = Recipe.find(params[:id])
    end

    def recipe_params
      params.require(:recipe).permit(:title, :description, :image, ingredients_attributes: [:id, :name, :_destroy], instructions_attributes: [:id, :step, :_destroy])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Recipes</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <nav class="navbar navbar-full navbar-light bg-faded">
    <div class="container">
      <%= link_to "Recipes", root_path, class: "navbar-brand" %>

      <ul class="nav navbar-nav">
        <li class="nav-item">
          <%= link_to "All Recipes", root_path, class: "nav-link" %>
        </li>
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to "Add New Recipe", new_recipe_path, class: "nav-link" %>
          </li>
          <li class="nav-item pull-xs-right">
            <%= link_to "Sign out", destroy_user_session_path, method: :delete, class: "nav-link pull-right" %>
          </li>
          <li class="nav-item pull-xs-right">
            <span class="nav-link">Hi <%= current_user.login %>!</span>
          </li>
        <% else %>

          <li class="nav-item pull-xs-right">
            <%= link_to "Sign in", new_user_session_path, class: "nav-link" %>
          </li>
          <li class="nav-item pull-xs-right">
            <%= link_to "Register", new_user_registration_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </nav>

<div class="container" style="margin-top: 20px;">
<% flash.each do |name, msg| %>
<div class="alert alert-<%= name %> alert-dismissible fade in" role="alert">
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
  <%= msg %>
</div>
<% end %>

<%= yield %>
</div>

</body>
</html>

app/views/recipes/_form.html.erb
<%= simple_form_for @recipe, html: {multipart: true} do |f| %>

	<% if @recipe.errors.any? %>
		<p><%= @recipe.errors.count %> meant that this couldn't save properly!</p>
		<ul>
			<% @recipe.errors.full_messages.each do |msg| %>
			<li><%= msg %></li>
			<% end %>
		</ul>
	<% end %>

	<div class="panel-body">
		<%= f.input :title, input_html: { class: 'form-control' } %>
		<%= f.input :description, input_html: { class: 'form-control' } %>
		<%= f.input :image, input_html: { class: 'form-control-file' } %>

		<div class="row">
			<div class="col-md-6">
				<h4>Ingredients</h4>
				<div id="ingredients">
					<%= f.simple_fields_for :ingredients do |ingredient| %>
						<%= render 'ingredient_fields', f: ingredient %>
					<% end %>
      		<%= link_to_add_association 'add ingredient', f, :ingredients, class: "btn btn-sm btn-default" %>
				</div>
			</div>

			<div class="col-md-6">
				<h4>Instructions</h4>
				<div id="instruction">
					<%= f.simple_fields_for :instructions do |instruction| %>
						<%= render 'instruction_fields', f: instruction %>
					<% end %>
      		<%= link_to_add_association 'add step', f, :instructions, class: "btn btn-sm btn-default" %>
				</div>
			</div>
		</div>
		<br>
		<p><%= f.button :submit, class: 'btn btn-primary' %></p>
		
	</div>

<% end %>

app/views/recipes/_ingredient_fields.html.erb
<div class="nested-fields">
  <%= f.input :name %>
  <%= link_to_remove_association "Remove", f %>
</div>
  

app/views/recipes/_instruction_fields.html.erb
<div class="form-inline clearfix">
  <div class="nested-fields">
    <%= f.input :step, class: 'form-input form-control' %>
    <%= link_to_remove_association "Remove", f, class: "form-button btn btn-sm" %>
  </div>
</div>

app/views/recipes/edit.html.erb
<h1>Edit Recipe</h1>

<%= render 'form' %>

<br>

<%= link_to 'Back', root_path, class: 'btn btn-default' %>

app/views/recipes/index.html.erb
<div class="row">
<% @recipe.each do |recipe| %>
  <%= link_to recipe, class: "col-md-3", style: "padding: 5px" do %>
    <div style="overflow: hidden; width: 100%; height: 200px; padding:0; border: #ccc 1px solid; border-radius: 5px; position: relative;">
      <% if recipe.image? %>
      <%= image_tag recipe.image.url(:medium) %>
      <% end %>
      <div class="" style="position: absolute; width: 100%; background: rgba(0,0,0,0.65); border-radius:0 0 5px 5px; height: 75px; bottom: 0; padding: 5px;">
        <h4 style="color: white"><%= recipe.title %></h4>
        <p class=""><small style="color: #ccc">Last updated <%= time_ago_in_words recipe.updated_at %> ago</small></p>
      </div>
    </div>

  <% end %>
<% end %>
</div>

app/views/recipes/new.html.erb
<h1>New Recipe</h1>

<%= render 'form' %>

<br>

<%= link_to 'Back', root_path, class: 'btn btn-default' %>

app/views/recipes/show.html.erb
<h1><%= @recipe.title %></h1>
<p><%= @recipe.description %></p>
<p>Added <%= time_ago_in_words @recipe.created_at %> ago</p>
<% if @recipe.user %>
<p>Added by <%= @recipe.user.login %>
<% end %>
<h4>Ingredients</h4>
<ul>
  <% @recipe.ingredients.each do |ingredient| %>
    <li><%= ingredient.name %></li>
  <% end %>
</ul>

<h4>Instructions</h4>
<ol>
  <% @recipe.instructions.each do |instruction| %>
    <li><%= instruction.step %></li>
  <% end %>
</ol>

<%= link_to "Edit", edit_recipe_path, class: "btn btn-sm btn-primary" %>
<%= link_to "Delete", recipe_path, method: :delete, data: {confirm: "Are you sure you want to delete this recipe? This cannot be undone!"}, class: "btn btn-sm btn-danger" %>

<%= link_to "Back to list", root_path, class: "btn btn-sm btn-default" %>